name: apex_lsp
description: Apex Language Server Protocol (LSP) server over stdio.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  apex_reflection:
    git:
      url: https://github.com/cesarParra/apex-reflection.git
  get_it: ^9.2.0
  ffi: ^2.1.0
  file: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.11.3
  lints: ^6.0.0
  test: ^1.29.0

executables:
  apex_lsp: apex_lsp
